### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by georgev93** [ChiefGokhlayeh/autofff#69]
I think the instructions in the README regarding how to use autofff as a python package are no longer correct. You mention you can do the following:

```python
import autofff

import os.path

targetHeader = input("Enter the path of the header you would like to scan: ")
outputHeader = input("Enter the path of the target header file which shall be generated: ")
fakes = './autofff/dependencies/pycparser/utils/fake_libc_include'

scnr = autofff.GCCScanner(targetHeader, fakes) # Create GCC code scanner
```

However, I don't think this works after this commit: 4ba015b. When you no longer do `from scanner import *` in the `__init__.py` file, you can't just use `autofff.GCCScanner()` after doing an `import autofff`.

I'm no python expert, but I was able to get the following to work:

```python
from autofff import scanner

targetHeader = input("Enter the path of the header you would like to scan: ")
outputHeader = input("Enter the path of the target header file which shall be generated: ")
fakes = './autofff/dependencies/pycparser/utils/fake_libc_include'

scnr = autofff.scanner.GCCScanner(targetHeader, fakes) # Create GCC code scanner
```

Perhaps there is a better way to do it. All I know is what is listed in the README didn't work for me

**Comment by ChiefGokhlayeh** [comment]
Thanks for the hint! I fixed the example in the README and added a rudimentary doctest to the Makefile build. This should catch inconsistencies in documentation in future.

**Comment by georgev93** [comment]
Woah... I hadn't heard of phmutest before, but it looks pretty slick! Nice fix!
