### ISSUE TITLE
pycparser version cap

### ISSUE THREAD

**Issue by s0be** [ChiefGokhlayeh/autofff#8]
pycparser 2.21 adds an align arg to a bunch of the constructors in 

https://github.com/eliben/pycparser/commit/14ffe7bc486805c568403757d8634211f8458451

Which breaks autofff.  Pinning pycparser to <=2.20 can resolve this.

**Comment by ChiefGokhlayeh** [comment]
Fixed in [`v0.4`](https://github.com/ChiefGokhlayeh/autofff/releases/tag/v0.4).

Thank you for pointing this out.
